version: '3.9'

services:
  asb-export-server:
    container_name: asb-export-server
    image: coldino/asb-export-server:latest
    restart: unless-stopped
    ports:
      - 4173:3000
    env_file: .env.live
    environment:
      # PROTOCOL_HEADER: "x-forwarded-proto"
      # HOST_HEADER: "x-forwarded-host"
      # ADDRESS_HEADER: "x-forwarded-for"
      # XFF_DEPTH: 1
      ORIGIN: 'http://localhost:4173'
